sunstar-foundation/sunstar-foundation

.github/pull_request_template.md, .github/visual-tests/run-locally.bash, .github/workflows/visual-tests.yaml, .renovaterc.json, README.md, blocks/consent-manager/consent-manager.css, package.json, scripts/scripts.js, tools/importer/import-footer.js, tools/importer/import-header.js, tools/importer/import-news-press-healthythinking.js, tools/importer/import-photo-gallery.js, tools/importer/import.js, tools/importer/utils.js, tools/sidekick/config.json
Test URLs:
- Original: https://www.sunstar-foundation.org
- Before: https://main--sunstar-foundation--sunstar-foundation.hlx.live
- After: https://adjust-repo--sunstar-foundation--sunstar-foundation.hlx.live
For e.g. cards (grid)  | [doc-link](https://main--sunstar-foundation--sunstar-foundation.hlx.page/tools/sidekick/library.html?plugin=blocks&path=/sidekick/blocks/cards&index=2)
=> Adjust org name

blocks/carousel/carousel.css, blocks/carousel/carousel.js, blocks/columns/columns.css, blocks/columns/columns.js, scripts/scripts.js, test/scripts/scripts.test.js
Test URLs:
- Before: https://main--sunstar-foundation--sunstar-foundation.hlx.live/<path>
- After: https://$branch--sunstar-foundation--sunstar-foundation.hlx.live/<path> …
=> Pull from Adobe Github

404.html
Fixes: #4
Test URLs:
- Original: https://www.sunstar-foundation.org/q
- Before: https://main--sunstar-foundation--sunstar-foundation.hlx.live/q
- After: https://issue-4b--sunstar-foundation--sunstar-foundation.hlx.live/q
=> Back to homepage button on 404 page goes to /jp

scripts/scripts.js
Open /en page in a new tab from the Home Page
Fixes #7 
Test URLs:
- Original: https://www.sunstar-foundation.org/
- Before: https://main--sunstar-foundation--hlxsites.hlx.live/
- After: https://issue-7--sunstar-foundation--hlxsites.hlx.live/
=> Issue 7: Open /en page in a new tab from the Home Page

blocks/cards/cards.css
https://github.com/hlxsites/sunstar-foundation/pull/226
Test URLs:
- Original: https://www.sunstar-foundation.org/en/education/jsdei/gallery
- Before: https://main--sunstar-foundation--sunstar-foundation.hlx.live/en/education/jsdei/gallery
- After: https://issue180--sunstar-foundation--sunstar-foundation.hlx.live/en/education/jsdei/gallery
Variation Name    | …
=> Fix padding in card view 

blocks/cards/cards.css, blocks/footer/footer.js, scripts/scripts.js
Test URLs:
- Before: https://main--sunstar-foundation--hlxsites.hlx.live/<path>
- After: https://main--sunstar-foundation--sunstar-foundation.hlx.live/<path>
For e.g. cards (grid)  | [doc-link](https://main--sunstar-foundation--sunstar-foundation.hl …
=> Pull from Adobe Repository

blocks/form/form.css
…ent for forms in sunstar.com as well
Fixes #11 
Test URLs:
- Before: https://issue11-form-resize--sunstar-foundation--sunstar-foundation.hlx.live/contact-form
- After: https://issue11-form-resize--sunstar-foundation--sunstar-foundation.hlx.live/contact-form
For e.g. …
=> Updating the max width as per customer request. Need to maintain consistency across sites for form width

blocks/embed/embed.css
Fixes #21 
Test URLs:
- Original: https://www.sunstar-foundation.org/for-healthcare-info/education
- Before: https://main--sunstar-foundation--sunstar-foundation.hlx.live/for-healthcare-info/education
- After: https://issue-21--sunstar-foundation--sunstar-foundation.hlx.live/for-healthcare-info/education
For e.g. cards …
=> Aspect ratio removed

blocks/cards/cards.css
Test URLs:
- Original: https://www.sunstar-foundation.org/grants
- Before: https://main--sunstar-foundation--hlxsites.hlx.live/grants
- After: https://main--sunstar-foundation--sunstar-foundation.hlx.live/grants
For e.g. cards (grid)  | [doc-link](https://main--sunstar-foundation--sunstar-foundation.hlx.page/tools/sidekick …
=> Fix stacked cards in tablet view (#229)

blocks/header/header.css, blocks/header/header.js
Fixes #8
Test URLs:
- Original: https://www.sunstar-foundation.org/dentistry
- Before: https://main--sunstar-foundation--sunstar-foundation.hlx.live/dentistry
- After: https://issue-8-v2--sunstar-foundation--sunstar-foundation.hlx.live/dentistry
=> issues-8 Fixed the Dentistry Header

blocks/overlapping-content/overlapping-content.css
Fixes #20 
Test URLs:
- Original: https://www.sunstar-foundation.org/dentistry/adult
- Before: https://main--sunstar-foundation--sunstar-foundation.hlx.live/dentistry/adult
- After: https://issue-20-v1--sunstar-foundation--sunstar-foundation.hlx.live/dentistry/adult
=> issue-20: Center download icon

blocks/header/header.css
Fixes #37 
Test URLs:
- Original: https://www.sunstar-foundation.org/dentistry/concept
- Before: https://main--sunstar-foundation--sunstar-foundation.hlx.page/dentistry/concept
- After: https://issue37--sunstar-foundation--sunstar-foundation.hlx.page/dentistry/concept …
=> Updating the css to fix the Mobile view

blocks/columns/columns.css, styles/styles.css
Test URLs:
- Before: https://main--sunstar-foundation--sunstar-foundation.hlx.live/<path>
- After: https://$branch--sunstar-foundation--sunstar-foundation.hlx.live/<path> …
=> Columns Dark Variant 

blocks/header/header.css
Test URLs:
- Before: https://main--sunstar-foundation--sunstar-foundation.hlx.live/<path>
- After: https://$branch--sunstar-foundation--sunstar-foundation.hlx.live/<path> …
=> header font size

blocks/carousel/carousel.css
Test URLs:
- Before: https://main--sunstar-foundation--sunstar-foundation.hlx.live/<path>
- After: https://$branch--sunstar-foundation--sunstar-foundation.hlx.live/<path> …
=> Carousel font size fix

blocks/hero-horizontal-tabs/hero-horizontal-tabs.css
Fixes #45 
Test URLs:
- Original: https://www.sunstar-foundation.org/grants/received-list
- Before: https://main--sunstar-foundation--sunstar-foundation.hlx.live/grants/received-list
- After: https://issue45--sunstar-foundation--sunstar-foundation.hlx.live/grants/received-list
=> Wide space shows in tab in FF

scripts/scripts.js
Fixes #49 
Test URLs:
- Original: https://www.sunstar-foundation.org/oral-care/school
- Before: https://main--sunstar-foundation--sunstar-foundation.hlx.live/oral-care/school
- After: https://issue-49--sunstar-foundation--sunstar-foundation.hlx.live/oral-care/school …
=> Issue-49 Modal Close fix

scripts/scripts.js
Fixes #52
Test URLs:
* Original: https://www.sunstar-foundation.org/
* Before: https://main--sunstar-foundation--sunstar-foundation.hlx.live/
* After: https://issue-52--sunstar-foundation--sunstar-foundation.hlx.live/
=> Improve loadScript

blocks/header/header.css, blocks/header/header.js
Test URLs:
- Original: https://www.sunstar-foundation.org/dentistry
- Before: https://main--sunstar-foundation--sunstar-foundation.hlx.live/dentistry
- After: https://cls-issue--sunstar-foundation--sunstar-foundation.hlx.live/dentistry …
=> CLS issue in header for Mobile view

blocks/header/header.css, blocks/header/header.js
Fixes 
Test URLs:
- Original: https://www.sunstar-foundation.org/
- Before: https://main--sunstar-foundation--sunstar-foundation.hlx.live/
- After: https://cls-changes--sunstar-foundation--sunstar-foundation.hlx.live/
For e.g. cards (grid)  | [doc-link](https://main--sunstar-foundation--sunstar-foundation.hlx.page/tools/si …
=> Review Comments incorporated

blocks/cards/cards.css, blocks/columns/columns.css, blocks/columns/columns.js, blocks/embed/embed.js
Test URLs:
- Original: https://www.sunstar-foundation.org/_drafts/youtube
- Before: https://main--sunstar-foundation--sunstar-foundation.hlx.page/_drafts/youtube
- After: https://new-cards--sunstar-foundation--sunstar-foundation.hlx.page/_drafts/youtube …
=> Added Youtube embed for columns components
